import "server-only";

/**
 * Cashfree Payments (PG) — SERVER ONLY.
 *
 * The gateway that collects money before we issue a TBO ticket or hotel voucher.
 * Raw REST + Node `crypto` rather than the `cashfree-pg` SDK, to match the repo's
 * provider style (see lib/tbo.ts) and avoid a dependency. The browser loads only
 * Cashfree's JS SDK (`@cashfreepayments/cashfree-js`) and opens the checkout with a
 * `payment_session_id`; everything that touches the secret key (order creation, order
 * lookup, refund, webhook verification) happens here on the server.
 *
 * Four rules a conventional gateway would let you break — read before "simplifying":
 *   • Cashfree does NOT hand the browser a signed payment receipt. `cashfree.checkout()`
 *     resolves with `paymentDetails`, but that object is client-side and unsigned, so it
 *     proves nothing. The ONLY trustworthy confirmation is a server-side Get Order /
 *     Get Payments call keyed by OUR `order_id` — that is what `confirmPaidOrder()` does.
 *   • Amounts are rupees with up to 2 decimals, NOT paise. Do not multiply by 100.
 *   • `order_id` is generated by us and must be unique per Create Order call.
 *   • Refunds are per ORDER (`POST /orders/{order_id}/refunds`), not per payment id.
 *
 * Flow ownership:
 *   1. /api/payment/order → validate + createOrder() for the authoritative FareQuote
 *      amount, binding the booking to the order via `order_tags.bind`
 *   2. Cashfree Checkout → customer pays
 *   3. /api/book → confirmPaidOrder() re-reads the order from Cashfree, checks it is
 *      PAID, checks the amount, and checks the bind tag matches THIS booking, all
 *      BEFORE calling TBO; refundOrder() if ticketing then fails.
 *
 * Everything degrades: with no keys `cashfreeConfigured` is false and the booking
 * routes fall back to their staging-only unpaid path (see lib/tbo-env.ts).
 */
import crypto from "node:crypto";

/** True once both credentials are present. Gates whether payment is enforced at all. */
export const cashfreeConfigured = Boolean(
  process.env.CASHFREE_APP_ID && process.env.CASHFREE_SECRET_KEY,
);

/**
 * Which Cashfree stack we talk to. Also handed to the browser so the JS SDK is
 * initialised in the matching mode — a sandbox session id will not open in a
 * production SDK and vice versa.
 *
 * Cashfree calls this environment "sandbox" in the SDK, "test" in the dashboard URL
 * (`?env=test`) and "prod" in the production one, so all the obvious spellings are
 * accepted rather than making one of them silently mean the other. Anything
 * unrecognised — including a typo'd "produciton" — resolves to sandbox: the failure
 * mode is then a checkout that won't open, never live money taken by accident.
 */
function resolveMode(raw: string | undefined): "sandbox" | "production" {
  const v = (raw ?? "").trim().toLowerCase();
  if (["production", "prod", "live"].includes(v)) return "production";
  if (v && !["sandbox", "test", "dev", "development"].includes(v)) {
    console.warn(`[cashfree] Unrecognised CASHFREE_ENV "${raw}" — defaulting to sandbox.`);
  }
  return "sandbox";
}

export const CASHFREE_MODE: "sandbox" | "production" = resolveMode(process.env.CASHFREE_ENV);

/**
 * True only when we can take REAL money: configured AND pointed at production.
 *
 * Distinct from `cashfreeConfigured` on purpose, and the distinction is load-bearing.
 * `cashfreeConfigured` answers "should the payment gate run?"; this answers "is the
 * money real?". Sandbox keys satisfy the first and not the second — and sandbox keys
 * against LIVE TBO credentials would issue a real ticket, or hold a real hotel room,
 * in exchange for play money. The live-host guards in lib/tbo-env.ts must therefore
 * be given THIS flag, never `cashfreeConfigured`.
 */
export const cashfreePaymentsLive = cashfreeConfigured && CASHFREE_MODE === "production";

const API =
  CASHFREE_MODE === "production" ? "https://api.cashfree.com/pg" : "https://sandbox.cashfree.com/pg";

/**
 * Pinned API version. Cashfree serves per-request response shapes off this header, so
 * pin it rather than inheriting whatever the dashboard defaults to. Override only after
 * re-reading the changed schema.
 *
 * NOTE: this pins the REST API only. Webhook payloads carry their own
 * `x-webhook-version`, set per-endpoint in the dashboard — match it to this value there
 * or the two drift apart silently.
 */
const API_VERSION = process.env.CASHFREE_API_VERSION || "2026-01-01";

export class CashfreeError extends Error {
  readonly status?: number;
  readonly code?: string;
  constructor(message: string, status?: number, code?: string) {
    super(message);
    this.name = "CashfreeError";
    this.status = status;
    this.code = code;
  }
}

type Json = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any

async function cf(path: string, opts: { method?: string; json?: unknown } = {}): Promise<Json> {
  const r = await fetch(`${API}${path}`, {
    method: opts.method ?? "GET",
    headers: {
      "x-api-version": API_VERSION,
      "x-client-id": process.env.CASHFREE_APP_ID ?? "",
      "x-client-secret": process.env.CASHFREE_SECRET_KEY ?? "",
      Accept: "application/json",
      ...(opts.json !== undefined ? { "Content-Type": "application/json" } : {}),
    },
    body: opts.json !== undefined ? JSON.stringify(opts.json) : undefined,
    cache: "no-store",
  });
  const text = await r.text();
  let data: Json;
  try {
    data = JSON.parse(text) as Json;
  } catch {
    throw new CashfreeError(`Cashfree returned a non-JSON response: ${text.slice(0, 120)}`, r.status);
  }
  if (!r.ok) {
    throw new CashfreeError(data?.message || `Cashfree request failed (${r.status}).`, r.status, data?.code);
  }
  return data;
}

// ── Binding a payment to a booking ────────────────────────────────────────────
// The client tells /api/book which order it paid. Without a binding check, a customer
// could pay for a ₹1 order and then present that order id against an expensive booking.
// So the order carries a hash of the booking's identity in `order_tags.bind`, and the
// book route recomputes it. Hashed rather than stored raw because a TBO ResultIndex or
// hotel BookingCode can be far longer than a tag value permits (255 chars).

/** Stable fingerprint of the thing being paid for. Written at order time, re-checked at book time. */
export function bindingHash(parts: string[]): string {
  return crypto.createHash("sha256").update(parts.join("|")).digest("hex");
}

/** The binding for a flight booking: the TBO trace + the exact fare being ticketed. */
export function flightBind(traceId: string, resultIndex: string): string {
  return bindingHash(["flight", traceId, resultIndex]);
}

/** The binding for a hotel booking: the PreBook rate the guest is paying for. */
export function hotelBind(bookingCode: string): string {
  return bindingHash(["hotel", bookingCode]);
}

/**
 * A fresh, unique `order_id`. Cashfree allows 3–45 chars of alphanumerics, `_` and `-`,
 * and rejects a repeat — so this is random, never derived from the booking.
 */
export function newOrderId(prefix: "rsf" | "rsh"): string {
  return `${prefix}_${crypto.randomBytes(14).toString("hex")}`; // 4 + 28 = 32 chars
}

// ── Orders ────────────────────────────────────────────────────────────────────

/**
 * Cashfree rejects any `order_expiry_time` under 15 minutes out
 * (`order_expiry_time_invalid`), so 16 is the tightest window we can actually ask for.
 *
 * That is LONGER than TBO's 15-minute TraceId, and no amount of tuning fixes it — the
 * two systems' floors simply don't overlap. So order expiry is not what protects us
 * from a stale fare. The real protection is downstream and already in place: /api/book
 * re-runs the whole TBO flow after payment and, if the TraceId has died, ticketing
 * fails and the payment is refunded automatically. Expiry here only stops an abandoned
 * checkout being paid days later; it is not a correctness boundary.
 */
const ORDER_EXPIRY_FLOOR_MIN = 16;

export type CfCustomer = {
  id: string;
  phone: string;
  email?: string;
  name?: string;
};

export type CfOrder = {
  order_id: string;
  cf_order_id?: string;
  order_amount: number; // rupees
  order_currency: string;
  order_status: string; // ACTIVE | PAID | EXPIRED | TERMINATED | TERMINATION_REQUESTED
  payment_session_id?: string;
  order_tags?: Record<string, string> | null;
};

/**
 * Create an order for `amountInr` (rupees, 2 dp — Cashfree is NOT paise-denominated).
 * Returns the `payment_session_id` the browser needs to open checkout.
 *
 * `customer.phone` is mandatory at Cashfree. Both callers take it from the lead
 * passenger/guest, which TBO already requires, so there is no invented fallback.
 */
export async function createOrder(args: {
  orderId: string;
  amountInr: number;
  customer: CfCustomer;
  tags?: Record<string, string>;
  note?: string;
  returnUrl?: string;
  /**
   * Minutes until the order can no longer be paid. Clamped to Cashfree's floor —
   * see ORDER_EXPIRY_FLOOR_MIN.
   */
  expiryMinutes?: number;
}): Promise<CfOrder> {
  const body: Json = {
    order_id: args.orderId,
    // Two decimals: TBO fares are displayed unrounded, so the charge must match.
    order_amount: Math.round(args.amountInr * 100) / 100,
    order_currency: "INR",
    customer_details: {
      customer_id: args.customer.id.slice(0, 50),
      customer_phone: args.customer.phone,
      ...(args.customer.email ? { customer_email: args.customer.email } : {}),
      ...(args.customer.name ? { customer_name: args.customer.name.slice(0, 100) } : {}),
    },
    ...(args.tags ? { order_tags: args.tags } : {}),
    ...(args.note ? { order_note: args.note.slice(0, 200) } : {}),
    ...(args.returnUrl ? { order_meta: { return_url: args.returnUrl } } : {}),
  };
  if (args.expiryMinutes) {
    const minutes = Math.max(args.expiryMinutes, ORDER_EXPIRY_FLOOR_MIN);
    body.order_expiry_time = new Date(Date.now() + minutes * 60_000).toISOString();
  }
  return cf("/orders", { method: "POST", json: body }) as Promise<CfOrder>;
}

export async function fetchOrder(orderId: string): Promise<CfOrder> {
  return cf(`/orders/${encodeURIComponent(orderId)}`) as Promise<CfOrder>;
}

export type CfPayment = {
  cf_payment_id: string;
  order_id?: string;
  payment_amount: number; // rupees
  payment_currency?: string;
  /** SUCCESS | NOT_ATTEMPTED | FAILED | USER_DROPPED | VOID | CANCELLED | PENDING */
  payment_status: string;
  payment_group?: string;
  payment_time?: string;
};

/** Every payment attempt against an order — an order can have several, at most one SUCCESS. */
export async function fetchOrderPayments(orderId: string): Promise<CfPayment[]> {
  const data = (await cf(`/orders/${encodeURIComponent(orderId)}/payments`)) as unknown;
  return Array.isArray(data) ? (data as CfPayment[]) : [];
}

export type ConfirmedOrder = {
  orderId: string;
  cfPaymentId: string;
  /**
   * What the customer was actually charged — Cashfree's `payment_amount`, not the
   * order total. Normally identical; they diverge only if a Cashfree offer or
   * surcharge is in play, and then the order total is the wrong number for every
   * downstream use (refund, booking mirror, refund email). One amount, one meaning:
   * money that actually left the customer.
   */
  amountInr: number;
  method?: string;
};

export type ConfirmResult =
  | { ok: true; payment: ConfirmedOrder }
  | { ok: false; error: string; unpaid: boolean };

/**
 * The gate every booking route runs before touching TBO.
 *
 * Re-reads the order FROM CASHFREE (never trusting anything the browser said), and
 * requires all three of:
 *   1. `order_status === "PAID"` — money actually moved;
 *   2. `order_tags.bind` matches this booking — the paid order is for THIS itinerary,
 *      not a cheaper one the customer paid for earlier;
 *   3. a payment row with `payment_status === "SUCCESS"` — gives us the `cf_payment_id`
 *      the ledger and any refund need.
 *
 * `unpaid: true` distinguishes "customer never completed payment" (a 402 the UI can
 * word gently) from "we could not verify" (a 502 that needs looking at).
 */
export async function confirmPaidOrder(args: {
  orderId: string;
  expectBind: string;
}): Promise<ConfirmResult> {
  const order = await fetchOrder(args.orderId);

  if (order.order_status !== "PAID") {
    return { ok: false, error: "This payment has not been completed.", unpaid: true };
  }
  if ((order.order_tags?.bind ?? "") !== args.expectBind) {
    // Paid, but for something else. Never ticket on it — and never refund it here
    // either; it belongs to whichever booking it was actually created for.
    return { ok: false, error: "This payment does not belong to this booking.", unpaid: false };
  }

  const payments = await fetchOrderPayments(args.orderId);
  const success = payments.find((p) => p.payment_status === "SUCCESS");
  if (!success) {
    return { ok: false, error: "This payment has not been completed.", unpaid: true };
  }

  return {
    ok: true,
    payment: {
      orderId: order.order_id,
      cfPaymentId: String(success.cf_payment_id),
      amountInr: Number(success.payment_amount),
      method: success.payment_group,
    },
  };
}

// ── Refunds ───────────────────────────────────────────────────────────────────

export type CfRefund = {
  cf_refund_id?: string;
  refund_id?: string;
  order_id?: string;
  refund_amount?: number;
  refund_status?: string; // SUCCESS | PENDING | CANCELLED | ONHOLD | FAILED
};

/**
 * Refund an order. Full refund unless `amountInr` is given.
 *
 * `refund_id` is OURS and must be unique per refund (3–40 alphanumerics); deriving it
 * from the order id makes a repeat call idempotent at Cashfree's end rather than
 * cutting a second refund — which matters because both booking routes call this from
 * an error path that may itself be retried.
 *
 * Always pass `confirmPaidOrder()`'s `amountInr`. Cashfree rejects a refund larger than
 * the transaction, so a number derived from anywhere else can silently fail.
 */
export async function refundOrder(
  orderId: string,
  opts?: { amountInr?: number; note?: string },
): Promise<CfRefund> {
  const refundId = `rf${orderId.replace(/[^a-zA-Z0-9]/g, "")}`.slice(0, 40);
  const json: Json = { refund_id: refundId };
  if (opts?.amountInr != null) json.refund_amount = Math.round(opts.amountInr * 100) / 100;
  if (opts?.note) json.refund_note = opts.note.slice(0, 100);
  return cf(`/orders/${encodeURIComponent(orderId)}/refunds`, {
    method: "POST",
    json,
  }) as Promise<CfRefund>;
}

// ── Webhooks ──────────────────────────────────────────────────────────────────

/**
 * Cashfree signs webhooks with the API SECRET KEY, not a separate webhook secret (the
 * override exists only for partner-key setups). So a configured gateway is a configured
 * webhook — there is no second env var to forget.
 */
export const cashfreeWebhookConfigured = Boolean(
  process.env.CASHFREE_WEBHOOK_SECRET || process.env.CASHFREE_SECRET_KEY,
);

function timingSafeEquals(expected: string, actual: string): boolean {
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(actual, "utf8");
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

/**
 * Verify a webhook: base64(HMAC-SHA256(`timestamp + rawBody`)) keyed by the secret,
 * compared to the `x-webhook-signature` header.
 *
 * The RAW body is required — re-serializing the parsed JSON rewrites decimals
 * (`170.00` → `170`) and the signature stops matching. Cashfree calls this out
 * explicitly, so the route reads req.text() and passes the bytes straight through.
 */
export function verifyWebhookSignature(
  rawBody: string,
  signature: string,
  timestamp: string,
): boolean {
  const secret = process.env.CASHFREE_WEBHOOK_SECRET || process.env.CASHFREE_SECRET_KEY || "";
  if (!secret || !signature || !timestamp) return false;
  const expected = crypto
    .createHmac("sha256", secret)
    .update(`${timestamp}${rawBody}`)
    .digest("base64");
  return timingSafeEquals(expected, signature);
}
