/**
 * Hotel destination types + the small client-safe "popular cities" list.
 *
 * The FULL dataset (43k+ TBO cities across 50+ countries) lives in
 * `hotel-cities.json`, generated by `scripts/fetch-hotel-cities.mjs` and read
 * ONLY on the server via `lib/hotel-city-search.ts` — never import the JSON
 * from a client component (it's ~2 MB). The search UI autocompletes against
 * `/api/hotels/cities` instead.
 */
export type HotelCity = {
  label: string;
  /** TBO CityCode passed to Search. */
  cityCode: string;
  countryCode: string;
};

/** Curated chips/suggestions — codes verified against the generated dataset. */
export const POPULAR_CITIES: HotelCity[] = [
  { label: "Delhi NCR", cityCode: "418069", countryCode: "IN" },
  { label: "Mumbai", cityCode: "144306", countryCode: "IN" },
  { label: "Goa", cityCode: "119805", countryCode: "IN" },
  { label: "Jaipur", cityCode: "122175", countryCode: "IN" },
  { label: "Udaipur", cityCode: "140522", countryCode: "IN" },
  { label: "Dubai", cityCode: "115936", countryCode: "AE" },
  { label: "Abu Dhabi", cityCode: "100765", countryCode: "AE" },
  { label: "Bangkok", cityCode: "144092", countryCode: "TH" },
  { label: "Phuket", cityCode: "131529", countryCode: "TH" },
  { label: "Singapore", cityCode: "138703", countryCode: "SG" },
  { label: "Bali (Denpasar)", cityCode: "116287", countryCode: "ID" },
  { label: "Kathmandu", cityCode: "145898", countryCode: "NP" },
  { label: "Colombo", cityCode: "144745", countryCode: "LK" },
  { label: "Malé", cityCode: "127096", countryCode: "MV" },
  { label: "London", cityCode: "126632", countryCode: "GB" },
  { label: "Paris", cityCode: "131408", countryCode: "FR" },
];
